# Generated by Django 2.2 on 2020-09-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PkiCertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('serial_number', models.IntegerField()),
                ('status', models.CharField(choices=[('V', 'valid'), ('R', 'revoked'), ('E', 'expired')], max_length=7)),
                ('subject', models.CharField(default='', max_length=512)),
                ('key_file', models.FileField(blank=True, default='', upload_to='')),
                ('cert_file', models.FileField(default='', upload_to='')),
                ('is_ca', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PkiCsrModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subject', models.CharField(default='', max_length=512)),
                ('csr_file', models.FileField(default='', upload_to='')),
                ('key_file', models.FileField(blank=True, default='', upload_to='')),
                ('is_ca', models.BooleanField(default=False)),
            ],
        ),
    ]
