# Generated by Django 2.2 on 2020-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0002_auto_20201010_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
