# Generated by Django 2.2 on 2020-10-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0004_auto_20201010_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='name',
            field=models.CharField(error_messages={'unique': 'This name has already been registered.'}, max_length=128, unique=True),
        ),
    ]
