# Generated by Django 2.2 on 2020-10-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0005_auto_20201010_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='cert_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='csr_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
