# Generated by Django 2.2 on 2020-10-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0007_pkiobjectmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkiobjectmodel',
            name='key_file_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
