# Generated by Django 2.2 on 2020-10-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0008_pkiobjectmodel_key_file_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkiobjectmodel',
            name='cert_file_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pkiobjectmodel',
            name='csr_file_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
