# Generated by Django 2.2 on 2020-10-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0009_auto_20201014_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkiobjectmodel',
            name='is_ca',
            field=models.BooleanField(default=False),
        ),
    ]
