# Generated by Django 2.2 on 2020-11-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0010_pkiobjectmodel_is_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkiobjectmodel',
            name='category',
            field=models.CharField(choices=[('LC', 'Local Cert'), ('EC', 'External Cert'), ('LCA', 'Local CA'), ('ECA', 'External CA'), ('CRL', 'CRL')], default='Local Cert', max_length=16),
        ),
    ]
