# Generated by Django 2.2 on 2020-11-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0012_auto_20201108_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='category',
            field=models.CharField(choices=[('Local CA', 'Local CA'), ('Local Cert', 'Local Cert'), ('Remote CA', 'Remote CA'), ('Remote Cert', 'Remote Cert'), ('CRL', 'CRL')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='pkiobjectmodel',
            unique_together={('category', 'name')},
        ),
    ]
