# Generated by Django 2.2 on 2020-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0014_auto_20201115_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='PkiCrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('crl_file', models.FileField(blank=True, default='', max_length=256, upload_to='')),
                ('crl_file_data', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='category',
            field=models.CharField(choices=[('Local CA', 'Local CA'), ('Local Cert', 'Local Cert'), ('Remote CA', 'Remote CA'), ('Remote Cert', 'Remote Cert')], max_length=16),
        ),
    ]
