# Generated by Django 2.2 on 2020-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0015_auto_20201117_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='PkiCaDatabaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crlnumber', models.TextField()),
                ('crlnumber_old', models.TextField()),
                ('index_txt', models.TextField()),
                ('index_txt_old', models.TextField()),
                ('index_attr', models.TextField()),
                ('index_attr_old', models.TextField()),
                ('serial', models.TextField()),
                ('serial_old', models.TextField()),
            ],
        ),
    ]
