# Generated by Django 2.2 on 2020-11-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_app', '0016_pkicadatabasemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkicadatabasemodel',
            name='crlnumber',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pkicadatabasemodel',
            name='crlnumber_old',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pkicadatabasemodel',
            name='index_attr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pkicadatabasemodel',
            name='index_attr_old',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pkicadatabasemodel',
            name='index_txt',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pkicadatabasemodel',
            name='index_txt_old',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pkicadatabasemodel',
            name='serial',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pkicadatabasemodel',
            name='serial_old',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pkicrlmodel',
            name='crl_file',
            field=models.FileField(blank=True, default='', max_length=128, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pkicrlmodel',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='cert_file',
            field=models.FileField(blank=True, default='', max_length=128, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='csr_file',
            field=models.FileField(blank=True, default='', max_length=128, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='key_file',
            field=models.FileField(blank=True, default='', max_length=128, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pkiobjectmodel',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='pkiobjectmodel',
            unique_together=set(),
        ),
    ]
